import java.io.*;
import java.util.ArrayList;
import java.util.Arrays;

/**Converts the .map files generated by the generator into .bls
 * Simple assumes the .map files contain only *, A-Z, and .'s
 */
public class MapToBLS {
    private static final String SAVE_FILE_PREFIX =
        "This is a Blockland save file.  You probably shouldn't modify it cause you'll screw it up.\n" +
        "1\n" +
        "\n" +
        "0.898039 0.000000 0.000000 1.000000\n" + //1 - 1
        "0.898039 0.898039 0.000000 1.000000\n" + //2
        "0.000000 0.498039 0.247059 1.000000\n" + //3
        "0.200000 0.000000 0.800000 1.000000\n" + //4
        "0.898039 0.898039 0.898039 1.000000\n" + //5
        "0.749020 0.749020 0.749020 1.000000\n" + //6
        "0.498039 0.498039 0.498039 1.000000\n" + //7
        "0.200000 0.200000 0.200000 1.000000\n" + //8
        "0.392157 0.192157 0.000000 1.000000\n" + //9
        "0.901961 0.337255 0.078431 1.000000\n" + //10
        "0.749020 0.176471 0.482353 1.000000\n" +
        "0.384314 0.000000 0.113725 1.000000\n" +
        "0.129412 0.266667 0.266667 1.000000\n" +
        "0.000000 0.137255 0.329412 1.000000\n" +
        "0.101961 0.458824 0.764706 1.000000\n" +
        "1.000000 1.000000 1.000000 1.000000\n" +
        "0.078431 0.078431 0.078431 1.000000\n" + //17
        "1.000000 1.000000 1.000000 0.247059\n" +
        "0.921569 0.513726 0.674510 1.000000\n" +
        "1.000000 0.603922 0.419608 1.000000\n" + //20
        "1.000000 0.874510 0.611765 1.000000\n" +
        "0.956863 0.874510 0.784314 1.000000\n" +
        "0.784314 0.921569 0.486275 1.000000\n" +
        "0.537255 0.694118 0.549020 1.000000\n" +
        "0.556863 0.929412 0.956863 1.000000\n" +
        "0.694118 0.658824 0.901961 1.000000\n" +
        "0.874510 0.556863 0.956863 1.000000\n" +
        "0.666667 0.000000 0.000000 0.698039\n" +
        "1.000000 0.498039 0.000000 0.698039\n" +
        "0.988235 0.956863 0.000000 0.698039\n" + //30
        "0.000000 0.470588 0.192157 0.698039\n" +
        "0.000000 0.200000 0.639216 0.698039\n" +
        "0.592157 0.156863 0.392157 0.694118\n" +
        "0.549020 0.698039 1.000000 0.698039\n" +
        "0.847059 0.847059 0.847059 0.698039\n" +
        "0.098039 0.098039 0.098039 0.698039\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" + //40
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000\n" +
        "1.000000 0.000000 1.000000 0.000000";

    private static final int COLOR_BLACK = 35;
    private static final int[] COLOR_ARRAY = {8, 0, 1, 2, 3, 5, 6, 8, 0, 1, 2, 3, 5, 6, 8, 0, 1, 2, 3, 5, 6, 8, 0, 1, 2, 3, 5, 6, 8, 0, 1, 2, 3, 5, 6, 8, 0, 1, 2, 3, 5, 6};
    private static final int COLOR_DARK_GREY = 6;

    public static void generateSimpleBLS(String fileName) throws Exception {
        BufferedReader br = new BufferedReader(new FileReader(new File(fileName)));
        String line = br.readLine();
        int brickCount = 0;
        while (line != null) {
            char[] lineContents = line.toCharArray();
            for (char c : lineContents) {
                if (c == '.' || c == '*' || (c >= 'A' && c <= 'Z')) {
                    brickCount++;
                }
            }

            line = br.readLine();
        }
        br = new BufferedReader(new FileReader(new File(fileName)));
        line = br.readLine();

        BufferedWriter bw = new BufferedWriter(new FileWriter("DUNGEON " + DUNGEON_NUMBER + ".bls"));
        bw.write(SAVE_FILE_PREFIX);
        bw.newLine();
        bw.write("Linecount " + brickCount);
        bw.newLine();


        String BRICK_NAME = "4x Cube\"";
        String position;
        String writeLine;

        int xPos = 2;
        int yPos = 2;
        int zPos = -1;
        //noinspection ConstantConditions
        while (line != null && !line.equals("")) {
            if (line.contains("Layer")) {
                zPos += 2;
                yPos = 2;
                line = br.readLine();
                continue;
            }

            char[] lineContents = line.toCharArray();

            for (int i = 0; i < lineContents.length; i++) {
                char c = lineContents[i];
                position = (xPos + (2 * i)) + " " + yPos + " " + zPos;
                if (c == '.') {
                    writeLine = makeSimpleBrickString(BRICK_NAME, position, COLOR_BLACK);
                } else if (c >= 'A' && c <= 'Z') {
                    writeLine = makeSimpleBrickString(BRICK_NAME, position, COLOR_ARRAY[c - 'A']);
                } else if (c == '*') {
                    writeLine = makeSimpleBrickExitString(" " + BRICK_NAME, position, COLOR_DARK_GREY);
                } else {
                    writeLine = null;
                }

                if (writeLine != null) {
                    bw.write(writeLine);
                    bw.newLine();
                }
            }

            yPos += 2;
            line = br.readLine();
        }

        br.close();

        bw.flush();
        bw.close();
    }

    private static String makeSimpleBrickString(String brick, String position, int color) {
        return brick + " " + position + " 0 0 " + color + "  0 0 1 1 1";
    }

    private static String makeSimpleBrickExitString(String brick, String position, int color) {
        return brick + " " + position + " 0 0 " + color + " Letters/A 0 0 1 1 1";
    }

    private static final int DUNGEON_NUMBER = 10;

    public static void main(String[] args) throws Exception {
        generateSimpleBLS("1.map");
    }
}
